<script>
  import Router, { location, link, querystring } from 'svelte-spa-router';
  import { open_search } from '@/stores.js';

  let open_search_value;

  open_search.subscribe((value) => {
    open_search_value = value;
  });

  function toggleSearch() {
    open_search.set(!open_search_value);
  }
</script>

<div class="fixed inset-0 z-50 flex items-start justify-center pt-16 sm:pt-24" class:hidden={!open_search_value} class:flex={open_search_value} id="headlessui-dialog-8" role="dialog" aria-modal="true">
  <div class="fixed inset-0 bg-slate-900/25 backdrop-blur transition-opacity opacity-100" on:click={toggleSearch}/>
  <div class="relative w-full max-w-1/2 transform px-4 transition-all opacity-100 scale-100">
    <div class="overflow-hidden rounded-lg bg-white shadow-md" id="headlessui-dialog-panel-11">
      <div class="relative">
        <input class="block w-full appearance-none bg-transparent py-4 pl-4 pr-12 text-base text-slate-900 placeholder:text-slate-600 focus:outline-none sm:text-sm sm:leading-6" placeholder="Find anything..." aria-label="Search components" id="headlessui-combobox-input-12" role="combobox" type="text" aria-expanded="false" tabindex="0" style="caret-color: rgb(107, 114, 128);" /><svg
          class="pointer-events-none absolute top-4 right-4 h-6 w-6 fill-slate-400"
          xmlns="http://www.w3.org/2000/svg"
          ><path
            d="M20.47 21.53a.75.75 0 1 0 1.06-1.06l-1.06 1.06Zm-9.97-4.28a6.75 6.75 0 0 1-6.75-6.75h-1.5a8.25 8.25 0 0 0 8.25 8.25v-1.5ZM3.75 10.5a6.75 6.75 0 0 1 6.75-6.75v-1.5a8.25 8.25 0 0 0-8.25 8.25h1.5Zm6.75-6.75a6.75 6.75 0 0 1 6.75 6.75h1.5a8.25 8.25 0 0 0-8.25-8.25v1.5Zm11.03 16.72-5.196-5.197-1.061 1.06 5.197 5.197 1.06-1.06Zm-4.28-9.97c0 1.864-.755 3.55-1.977 4.773l1.06 1.06A8.226 8.226 0 0 0 18.75 10.5h-1.5Zm-1.977 4.773A6.727 6.727 0 0 1 10.5 17.25v1.5a8.226 8.226 0 0 0 5.834-2.416l-1.061-1.061Z"
          /></svg
        >
      </div>
      <ul class="max-h-[18.375rem] divide-y divide-slate-200 overflow-y-auto rounded-b-lg border-t border-slate-200 text-sm leading-6 &>" role="listbox" id="headlessui-combobox-options-13">
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-14" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Action Panels</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Forms</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-15" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Alerts</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Feedback</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-16" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Avatars</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Elements</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-17" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Stacked Layouts</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Application Shells</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-18" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Sidebar Layouts</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Application Shells</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-19" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Multi-Column Layouts</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Application Shells</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-20" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Description Lists</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Data Display</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-21" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Stats</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Data Display</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-22" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Calendars</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Data Display</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-23" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Badges</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Elements</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-24" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Buttons</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Elements</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-25" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Button Groups</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Elements</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-26" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Dropdowns</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Elements</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-27" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Empty States</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Feedback</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-28" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Form Layouts</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Forms</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-29" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Input Groups</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Forms</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-30" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Select Menus</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Forms</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-31" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Textareas</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Forms</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-32" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Radio Groups</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Forms</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-33" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Checkboxes</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Forms</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-34" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Toggles</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Forms</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-35" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Sign-in and Registration</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Forms</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-36" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Comboboxes</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Forms</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-37" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Page Headings</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Headings</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-38" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Card Headings</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Headings</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-39" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Section Headings</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Headings</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-40" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Containers</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Layout</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-41" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Panels</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Layout</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-42" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">List containers</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Layout</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-43" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Media Objects</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Layout</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-44" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Dividers</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Layout</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-45" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Tables</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Lists</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-46" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Stacked Lists</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Lists</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-47" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Grid Lists</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Lists</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-48" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Feeds</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Lists</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-49" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Tabs</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Navigation</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-50" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Navbars</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Navigation</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-51" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Vertical Navigation</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Navigation</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-52" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Pagination</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Navigation</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-53" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Sidebar Navigation</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Navigation</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-54" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Breadcrumbs</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Navigation</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-55" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Steps</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Navigation</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-56" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Command Palettes</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Navigation</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-57" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Modals</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Overlays</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-58" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Slide-overs</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Overlays</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-59" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Notifications</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Overlays</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-60" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Home Screens</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Page Examples</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-61" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Detail Screens</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Page Examples</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-62" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Settings Screens</span><span class="ml-4 text-right text-xs text-slate-600">Application UI / Page Examples</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-63" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">404 Pages</span><span class="ml-4 text-right text-xs text-slate-600">Marketing / Feedback</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-64" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Banners</span><span class="ml-4 text-right text-xs text-slate-600">Marketing / Elements</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-65" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Category Filters</span><span class="ml-4 text-right text-xs text-slate-600">Ecommerce / Components</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-66" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Category Pages</span><span class="ml-4 text-right text-xs text-slate-600">Ecommerce / Page Examples</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-67" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Category Previews</span><span class="ml-4 text-right text-xs text-slate-600">Ecommerce / Components</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-68" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Checkout Pages</span><span class="ml-4 text-right text-xs text-slate-600">Ecommerce / Page Examples</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-69" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Contact Pages</span><span class="ml-4 text-right text-xs text-slate-600">Marketing / Page Examples</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-70" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Contact Sections</span><span class="ml-4 text-right text-xs text-slate-600">Marketing / Page Sections</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-71" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">CTA Sections</span><span class="ml-4 text-right text-xs text-slate-600">Marketing / Page Sections</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-72" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">FAQs</span><span class="ml-4 text-right text-xs text-slate-600">Marketing / Page Sections</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-73" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Feature Sections</span><span class="ml-4 text-right text-xs text-slate-600">Marketing / Page Sections</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-74" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Header Sections</span><span class="ml-4 text-right text-xs text-slate-600">Marketing / Page Sections</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-75" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Headers</span><span class="ml-4 text-right text-xs text-slate-600">Marketing / Elements</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-76" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Landing Pages</span><span class="ml-4 text-right text-xs text-slate-600">Marketing / Page Examples</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-77" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Order Detail Pages</span><span class="ml-4 text-right text-xs text-slate-600">Ecommerce / Page Examples</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-78" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Order History Pages</span><span class="ml-4 text-right text-xs text-slate-600">Ecommerce / Page Examples</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-79" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Order Summaries</span><span class="ml-4 text-right text-xs text-slate-600">Ecommerce / Components</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-80" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Pricing Pages</span><span class="ml-4 text-right text-xs text-slate-600">Marketing / Page Examples</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-81" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Product Features</span><span class="ml-4 text-right text-xs text-slate-600">Ecommerce / Components</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-82" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Product Pages</span><span class="ml-4 text-right text-xs text-slate-600">Ecommerce / Page Examples</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-83" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Shopping Cart Pages</span><span class="ml-4 text-right text-xs text-slate-600">Ecommerce / Page Examples</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-84" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Shopping Carts</span><span class="ml-4 text-right text-xs text-slate-600">Ecommerce / Components</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-85" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Stats</span><span class="ml-4 text-right text-xs text-slate-600">Marketing / Page Sections</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-86" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Store Navigation</span><span class="ml-4 text-right text-xs text-slate-600">Ecommerce / Components</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-87" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Storefront Pages</span><span class="ml-4 text-right text-xs text-slate-600">Ecommerce / Page Examples</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-88" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Team Sections</span><span class="ml-4 text-right text-xs text-slate-600">Marketing / Page Sections</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-89" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Testimonials</span><span class="ml-4 text-right text-xs text-slate-600">Marketing / Page Sections</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-90" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Flyout Menus</span><span class="ml-4 text-right text-xs text-slate-600">Marketing / Elements</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-91" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Hero Sections</span><span class="ml-4 text-right text-xs text-slate-600">Marketing / Page Sections</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-92" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Pricing Sections</span><span class="ml-4 text-right text-xs text-slate-600">Marketing / Page Sections</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-93" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Newsletter Sections</span><span class="ml-4 text-right text-xs text-slate-600">Marketing / Page Sections</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-94" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Blog Sections</span><span class="ml-4 text-right text-xs text-slate-600">Marketing / Page Sections</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-95" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Content Sections</span><span class="ml-4 text-right text-xs text-slate-600">Marketing / Page Sections</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-96" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Footers</span><span class="ml-4 text-right text-xs text-slate-600">Marketing / Page Sections</span></li>
        <li class="flex items-center justify-between p-4" id="headlessui-combobox-option-97" role="option" tabindex="-1"><span class="whitespace-nowrap font-semibold text-slate-900">Logo Clouds</span><span class="ml-4 text-right text-xs text-slate-600">Marketing / Page Sections</span></li>
      </ul>
    </div>
  </div>
</div>
